{% set name = "qt-async-threads" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qt-async-threads-{{ version }}.tar.gz
  sha256: 6ba5561c9bc604fb3a30f1c7492a4804e8beeb5d1a8d37495677f8f0394eaf0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools
    - setuptools-scm
  run:
    - attrs
    - boltons
    - python >=3.10
    - qtpy

test:
  requires:
    - PySide6
  imports:
    - qt_async_threads
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://qt-async-threads.readthedocs.io/
  summary: Use convenient async/await syntax to spawn threads in Qt applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
