{% set python_min = '3.10' %}
{% set name = "qt-async-threads" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qt-async-threads-{{ version }}.tar.gz
  sha256: 921973c8d7f67b1b9891f0114f335adb1bacaf7eb7b4bc1fa54afbbfb7711279

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - attrs
    - boltons
    - python >={{ python_min }}
    - qtpy

test:
  imports:
    - qt_async_threads
  commands:
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://qt-async-threads.readthedocs.io/
  summary: Use convenient async/await syntax to spawn threads in Qt applications
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
